#!/usr/bin/env bash
# Generate Claude CLI / Claude Code skill files from src/prompts/*.md.
#
# The markdown files under src/prompts/ are the single source of truth for
# the runbook. This script stamps them into .claude/skills/ with the right
# frontmatter so Claude CLI and Claude Code can load them.
#
# We deliberately do NOT generate .claude/agents/transaction-creator.md
# anymore: subagents in Claude Code inherit only pre-materialized MCP tools
# from the parent session, so a subagent can't reliably see our MCP tools
# via ToolSearch. Running the runbook inline in the skill (main-chat context)
# avoids this and is functionally equivalent.
#
# Run from package.json's build script (npm run gen). Idempotent.

set -euo pipefail

cd "$(dirname "$0")/.."

SRC_CREATE="src/prompts/create_transaction.md"
SRC_LISTING="src/prompts/create_listing.md"
SRC_FROM_DOC="src/prompts/create_from_document.md"
SRC_REFERRAL_PAYMENT="src/prompts/create_referral_payment.md"
SRC_UPDATE="src/prompts/update_draft.md"
SRC_SUBMIT="src/prompts/submit_draft.md"
SRC_DELETE="src/prompts/delete_draft.md"
SRC_LIST="src/prompts/list_drafts.md"

for f in "$SRC_CREATE" "$SRC_LISTING" "$SRC_FROM_DOC" "$SRC_REFERRAL_PAYMENT" "$SRC_UPDATE" "$SRC_SUBMIT" "$SRC_DELETE" "$SRC_LIST"; do
  if [[ ! -f "$f" ]]; then
    echo "✗ Source prompt file missing: $f" >&2
    exit 1
  fi
done

# resume-draft was merged into update-draft (2026-05-07). Clean up any stale
# generated skill folder so Claude Code doesn't load the deleted runbook.
rm -rf .claude/skills/resume-draft

mkdir -p .claude/skills/create-transaction \
  .claude/skills/create-listing .claude/skills/create-from-document \
  .claude/skills/create-referral-payment \
  .claude/skills/update-draft .claude/skills/submit-draft \
  .claude/skills/delete-draft .claude/skills/list-drafts

# Remove any previously-generated marketplace-referral skill folder if present.
rm -rf .claude/skills/create-referral

# ---- create-transaction skill (natural-language trigger) ----
cat > .claude/skills/create-transaction/SKILL.md <<'HEADER'
---
name: create-transaction
description: Create a Real Brokerage draft transaction from a plain-English prompt. Triggers when the user says "create a transaction", "new draft transaction", "build a transaction for me", "start a draft for ...", or similar phrasing that describes a real-estate deal. Follow the runbook below directly — do NOT delegate to a subagent (the transaction-builder MCP tools are only reliably accessible in the main chat context, not subagent contexts).
---

<!-- AUTO-GENERATED from src/prompts/create_transaction.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_CREATE" >> .claude/skills/create-transaction/SKILL.md

# ---- create-listing skill ----
cat > .claude/skills/create-listing/SKILL.md <<'HEADER'
---
name: create-listing
description: Create a Real Brokerage listing from a plain-English prompt. Triggers when the user says "create a listing", "new listing", "list this property", "add listing for …", or describes putting a property on the market. Uses the same transaction-builder infrastructure as transactions but with type=LISTING (5 steps, no buyers, listingDate + listingExpirationDate).
---

<!-- AUTO-GENERATED from src/prompts/create_listing.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_LISTING" >> .claude/skills/create-listing/SKILL.md

# ---- create-from-document skill (PDF / image → transaction or listing) ----
cat > .claude/skills/create-from-document/SKILL.md <<'HEADER'
---
name: create-from-document
description: Create a Real Brokerage transaction or listing from a PDF or image of a real-estate document (listing agreement, purchase/sale contract, buyer-rep agreement). Triggers when the user supplies a document file and asks to create/start a transaction or listing from it — e.g. "read this PDF and create the transaction", "start a listing from this agreement", "create a transaction from this contract", or provides a .pdf/.png/.jpg path. Reads the document with the multimodal Read tool, extracts ONLY filled-in terms (never fabricating from blank fields or form annotations), confirms the extraction, then hands off to create-listing (listing agreement) or create-transaction (sale contract).
---

<!-- AUTO-GENERATED from src/prompts/create_from_document.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_FROM_DOC" >> .claude/skills/create-from-document/SKILL.md

# ---- create-referral-payment skill ----
cat > .claude/skills/create-referral-payment/SKILL.md <<'HEADER'
---
name: create-referral-payment
description: Record a referral payment as a standalone transaction on Real's books (the "Create Referral / Payment" button in Bolt). Triggers when the user says "create a referral payment", "record a referral fee", "external agent owes me a referral", "I got a referral payment", "add the referral to my books", or describes a referral between agents NOT attached to a sale they are also closing. Different from add_referral (line item on a sale transaction). arrakis has NO draft stage for this flow — the runbook shows a full in-chat preview in the same turn as the single create-and-disburse POST, so the user can interrupt with Esc if anything's wrong. No "are you sure?" confirm button.
---

<!-- AUTO-GENERATED from src/prompts/create_referral_payment.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_REFERRAL_PAYMENT" >> .claude/skills/create-referral-payment/SKILL.md

# ---- update-draft skill ----
cat > .claude/skills/update-draft/SKILL.md <<'HEADER'
---
name: update-draft
description: Modify or resume an existing draft (transaction-builder). Two intents — explicit mutations ("change price", "add partner Y", "flip to installments") OR resume-toward-submittable ("resume the draft", "pick up where I left off", "finish that draft from earlier"). Auto-picks the most-recent in-flight draft when no target is named in resume intent. Triggers on "update draft X", "change/set/add/remove on draft", "resume/finish/continue the draft", or any builderId reference with a mutation/gap-fill intent.
---

<!-- AUTO-GENERATED from src/prompts/update_draft.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_UPDATE" >> .claude/skills/update-draft/SKILL.md

# ---- submit-draft skill ----
cat > .claude/skills/submit-draft/SKILL.md <<'HEADER'
---
name: submit-draft
description: Submit a draft transaction or listing — promote the builder to a live Transaction / LISTING_ACTIVE. Triggers when the user says "submit draft X", "finalize the draft", "send it", "make it official", "submit my last draft". Runs pre-submit sanity, POSTs /transaction-builder/{id}/submit, and surfaces warnings.
---

<!-- AUTO-GENERATED from src/prompts/submit_draft.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_SUBMIT" >> .claude/skills/submit-draft/SKILL.md

# ---- delete-draft skill ----
cat > .claude/skills/delete-draft/SKILL.md <<'HEADER'
---
name: delete-draft
description: Permanently delete an unsubmitted draft from arrakis. Triggers when the user says "delete draft X", "cancel the draft", "throw away the draft", "abandon the draft", "scrap this one". Irreversible — runbook previews what's being deleted before firing DELETE /transaction-builder/{id}. For SUBMITTED transactions use termination, not this.
---

<!-- AUTO-GENERATED from src/prompts/delete_draft.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_DELETE" >> .claude/skills/delete-draft/SKILL.md

# ---- list-drafts skill ----
cat > .claude/skills/list-drafts/SKILL.md <<'HEADER'
---
name: list-drafts
description: Show the user's in-flight (unsubmitted) drafts. Triggers when the user says "what drafts do I have", "list my drafts", "show pending drafts", "any open drafts", "show me my last N drafts". Read-only — lists builderId, type, property, amount, status, and offers row-number shortcuts for follow-up actions.
---

<!-- AUTO-GENERATED from src/prompts/list_drafts.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_LIST" >> .claude/skills/list-drafts/SKILL.md

# batch-create was retired (2026-05-28). Clean up any stale generated folder.
rm -rf .claude/skills/batch-create

# sync-rules was retired (2026-05-28). Clean up any stale generated folder.
rm -rf .claude/skills/sync-rules

# Delete any previously-generated subagent file if still present (legacy).
if [[ -f .claude/agents/transaction-creator.md ]]; then
  rm -f .claude/agents/transaction-creator.md
  echo "  ✗ Removed legacy .claude/agents/transaction-creator.md (subagents don't work with our MCP pattern)."
fi
# Remove empty .claude/agents if we created it previously and it's now empty.
if [[ -d .claude/agents ]] && [[ -z "$(ls -A .claude/agents 2>/dev/null)" ]]; then
  rmdir .claude/agents
fi

echo "✓ CLI wrappers generated from src/prompts/*.md"
echo "  .claude/skills/create-transaction/SKILL.md"
echo "  .claude/skills/create-listing/SKILL.md"
echo "  .claude/skills/create-from-document/SKILL.md"
echo "  .claude/skills/create-referral-payment/SKILL.md"
echo "  .claude/skills/update-draft/SKILL.md"
echo "  .claude/skills/submit-draft/SKILL.md"
echo "  .claude/skills/delete-draft/SKILL.md"
echo "  .claude/skills/list-drafts/SKILL.md"
