#!/usr/bin/env bash
# Generate Claude CLI / Claude Code skill files from src/prompts/*.md.
#
# The markdown files under src/prompts/ are the single source of truth for
# the runbook. This script stamps them into .claude/skills/ with the right
# frontmatter so Claude CLI and Claude Code can load them.
#
# We deliberately do NOT generate .claude/agents/transaction-creator.md
# anymore: subagents in Claude Code inherit only pre-materialized MCP tools
# from the parent session, so a subagent can't reliably see our MCP tools
# via ToolSearch. Running the runbook inline in the skill (main-chat context)
# avoids this and is functionally equivalent.
#
# Run from package.json's build script (npm run gen). Idempotent.

set -euo pipefail

cd "$(dirname "$0")/.."

SRC_CREATE="src/prompts/create_transaction.md"
SRC_SYNC="src/prompts/sync_rules.md"
SRC_RESUME="src/prompts/resume_draft.md"
SRC_LISTING="src/prompts/create_listing.md"
SRC_REFERRAL="src/prompts/create_referral.md"
SRC_REFERRAL_PAYMENT="src/prompts/create_referral_payment.md"
SRC_UPDATE="src/prompts/update_draft.md"
SRC_SUBMIT="src/prompts/submit_draft.md"
SRC_DELETE="src/prompts/delete_draft.md"
SRC_LIST="src/prompts/list_drafts.md"

for f in "$SRC_CREATE" "$SRC_SYNC" "$SRC_RESUME" "$SRC_LISTING" "$SRC_REFERRAL" "$SRC_REFERRAL_PAYMENT" "$SRC_UPDATE" "$SRC_SUBMIT" "$SRC_DELETE" "$SRC_LIST"; do
  if [[ ! -f "$f" ]]; then
    echo "✗ Source prompt file missing: $f" >&2
    exit 1
  fi
done

mkdir -p .claude/skills/create-transaction .claude/skills/sync-rules \
  .claude/skills/resume-draft .claude/skills/create-listing \
  .claude/skills/create-referral .claude/skills/create-referral-payment \
  .claude/skills/update-draft .claude/skills/submit-draft \
  .claude/skills/delete-draft .claude/skills/list-drafts

# ---- create-transaction skill (natural-language trigger) ----
cat > .claude/skills/create-transaction/SKILL.md <<'HEADER'
---
name: create-transaction
description: Create a Real Brokerage draft transaction from a plain-English prompt. Triggers when the user says "create a transaction", "new draft transaction", "build a transaction for me", "start a draft for ...", or similar phrasing that describes a real-estate deal. Follow the runbook below directly — do NOT delegate to a subagent (the transaction-builder MCP tools are only reliably accessible in the main chat context, not subagent contexts).
---

<!-- AUTO-GENERATED from src/prompts/create_transaction.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_CREATE" >> .claude/skills/create-transaction/SKILL.md

# ---- sync-rules skill ----
cat > .claude/skills/sync-rules/SKILL.md <<'HEADER'
---
name: sync-rules
description: Force a full re-read of every watched arrakis path and rebuild memory/transaction-rules.md from scratch. Use when the user says "sync the rules", "update the rules", "refresh the logic", or suspects the tool is behind a recent Real change. Follow the runbook below directly in the main chat.
---

<!-- AUTO-GENERATED from src/prompts/sync_rules.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_SYNC" >> .claude/skills/sync-rules/SKILL.md

# ---- resume-draft skill ----
cat > .claude/skills/resume-draft/SKILL.md <<'HEADER'
---
name: resume-draft
description: Pick up a half-finished draft transaction from memory/active-drafts.md (or a user-supplied builderId), fill in what's missing, and finalize without overwriting correct fields. Triggers when the user says "resume the draft", "pick up where I left off", "finish that draft from earlier", "continue the last transaction", or references a specific builderId.
---

<!-- AUTO-GENERATED from src/prompts/resume_draft.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_RESUME" >> .claude/skills/resume-draft/SKILL.md

# ---- create-listing skill ----
cat > .claude/skills/create-listing/SKILL.md <<'HEADER'
---
name: create-listing
description: Create a Real Brokerage listing from a plain-English prompt. Triggers when the user says "create a listing", "new listing", "list this property", "add listing for …", or describes putting a property on the market. Uses the same transaction-builder infrastructure as transactions but with type=LISTING (5 steps, no buyers, listingDate + listingExpirationDate).
---

<!-- AUTO-GENERATED from src/prompts/create_listing.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_LISTING" >> .claude/skills/create-listing/SKILL.md

# ---- create-referral skill ----
cat > .claude/skills/create-referral/SKILL.md <<'HEADER'
---
name: create-referral
description: Post a marketplace referral via Real's Referral Central. Triggers when the user says "post a referral", "find an agent for my client", "refer out a buyer", "I have a client looking for …", or "marketplace referral". Different from paying a referral fee on a transaction (that uses /create-transaction with add_referral).
---

<!-- AUTO-GENERATED from src/prompts/create_referral.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_REFERRAL" >> .claude/skills/create-referral/SKILL.md

# ---- create-referral-payment skill ----
cat > .claude/skills/create-referral-payment/SKILL.md <<'HEADER'
---
name: create-referral-payment
description: Record a referral payment as a standalone transaction on Real's books (the "Create Referral / Payment" button in Bolt). Triggers when the user says "create a referral payment", "record a referral fee", "external agent owes me a referral", "I got a referral payment", "add the referral to my books", or describes a referral between agents NOT attached to a sale they are also closing. Different from /create-referral (marketplace) and add_referral (line item on a sale transaction). arrakis has NO draft stage for this flow — runbook requires an in-chat preview + explicit confirm before firing the single create-and-disburse POST.
---

<!-- AUTO-GENERATED from src/prompts/create_referral_payment.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_REFERRAL_PAYMENT" >> .claude/skills/create-referral-payment/SKILL.md

# ---- update-draft skill ----
cat > .claude/skills/update-draft/SKILL.md <<'HEADER'
---
name: update-draft
description: Modify any field on an existing draft transaction-builder. Routes natural-language mutations (price, commission, team, buyer/seller name, co-agent, dates, installments, representation) to the right granular MCP tool. Triggers when the user says "update draft X", "change {field} to {value}", "add/remove {participant} on draft", "set {flag}", or references a builderId with a mutation intent. Different from /resume-draft (which fills gaps toward submittable) — this handles arbitrary edits.
---

<!-- AUTO-GENERATED from src/prompts/update_draft.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_UPDATE" >> .claude/skills/update-draft/SKILL.md

# ---- submit-draft skill ----
cat > .claude/skills/submit-draft/SKILL.md <<'HEADER'
---
name: submit-draft
description: Submit a draft transaction or listing — promote the builder to a live Transaction / LISTING_ACTIVE. Triggers when the user says "submit draft X", "finalize the draft", "send it", "make it official", "submit my last draft". Runs pre-submit sanity, POSTs /transaction-builder/{id}/submit, and surfaces warnings.
---

<!-- AUTO-GENERATED from src/prompts/submit_draft.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_SUBMIT" >> .claude/skills/submit-draft/SKILL.md

# ---- delete-draft skill ----
cat > .claude/skills/delete-draft/SKILL.md <<'HEADER'
---
name: delete-draft
description: Permanently delete an unsubmitted draft from arrakis. Triggers when the user says "delete draft X", "cancel the draft", "throw away the draft", "abandon the draft", "scrap this one". Irreversible — runbook previews what's being deleted before firing DELETE /transaction-builder/{id}. For SUBMITTED transactions use termination, not this.
---

<!-- AUTO-GENERATED from src/prompts/delete_draft.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_DELETE" >> .claude/skills/delete-draft/SKILL.md

# ---- list-drafts skill ----
cat > .claude/skills/list-drafts/SKILL.md <<'HEADER'
---
name: list-drafts
description: Show the user's in-flight (unsubmitted) drafts. Triggers when the user says "what drafts do I have", "list my drafts", "show pending drafts", "any open drafts", "show me my last N drafts". Read-only — lists builderId, type, property, amount, status, and offers row-number shortcuts for follow-up actions.
---

<!-- AUTO-GENERATED from src/prompts/list_drafts.md — do NOT edit this file directly. Edit the source and re-run `npm run build`. -->

HEADER
cat "$SRC_LIST" >> .claude/skills/list-drafts/SKILL.md

# Delete any previously-generated subagent file if still present (legacy).
if [[ -f .claude/agents/transaction-creator.md ]]; then
  rm -f .claude/agents/transaction-creator.md
  echo "  ✗ Removed legacy .claude/agents/transaction-creator.md (subagents don't work with our MCP pattern)."
fi
# Remove empty .claude/agents if we created it previously and it's now empty.
if [[ -d .claude/agents ]] && [[ -z "$(ls -A .claude/agents 2>/dev/null)" ]]; then
  rmdir .claude/agents
fi

echo "✓ CLI wrappers generated from src/prompts/*.md"
echo "  .claude/skills/create-transaction/SKILL.md"
echo "  .claude/skills/sync-rules/SKILL.md"
echo "  .claude/skills/resume-draft/SKILL.md"
echo "  .claude/skills/create-listing/SKILL.md"
echo "  .claude/skills/create-referral/SKILL.md"
echo "  .claude/skills/create-referral-payment/SKILL.md"
echo "  .claude/skills/update-draft/SKILL.md"
echo "  .claude/skills/submit-draft/SKILL.md"
echo "  .claude/skills/delete-draft/SKILL.md"
echo "  .claude/skills/list-drafts/SKILL.md"
